### ISSUE TITLE
Questions about how incoming parameters are handled？

### ISSUE THREAD

**Issue by SivanCola** [vector4wang/elasticsearch-quick#3]
你好，我想实现的是一个搜索引擎的功能，不是基于关键字搜索，而是基于一句话搜索。
使用new ElasticsearchRepository的方法进行搜索的，生成了一个方法，比如说findByQuestion(String question)。在运行springboot后，想传入“how are you”报错，只能传入“how” 或者“are"或者“you”才不会报错，但是这样结果不精确。
请问有办法让后端直接去es里搜索一句话“how are you”吗？麻烦点拨下

**Comment by vector4wang** [comment]
具体是哪一个branch

**Comment by SivanCola** [comment]
> 具体是哪一个branch

 sb-jest-base 这个。不过我问的问题跟这个branch关系不太大，单纯的关于elasticsearch的，不知道您有无这方面的研究？

**Comment by vector4wang** [comment]
> 在运行springboot后，想传入“how are you”报错，只能传入“how” 或者“are"或者“you”才不会报错，

这个跟es无关，跟springboot有关系，首先确定“how are you” 能否到达后端！

**Comment by SivanCola** [comment]
> > 在运行springboot后，想传入“how are you”报错，只能传入“how” 或者“are"或者“you”才不会报错，
> 
> 这个跟es无关，跟springboot有关系，首先确定“how are you” 能否到达后端！

我之前已经确认过了，后端可以收到“how are you”,但是 esRepository.findByQuestion("how are you")就会报错~ 不知道为什么，难道是es把传入的“how are you”分词了？

**Comment by vector4wang** [comment]
> > > 在运行springboot后，想传入“how are you”报错，只能传入“how” 或者“are"或者“you”才不会报错，
> > 
> > 
> > 这个跟es无关，跟springboot有关系，首先确定“how are you” 能否到达后端！
> 
> 我之前已经确认过了，后端可以收到“how are you”,但是 esRepository.findByQuestion("how are you")就会报错~ 不知道为什么，难道是es把传入的“how are you”分词了？

好的，我有空看一下

**Comment by vector4wang** [comment]
> > > 在运行springboot后，想传入“how are you”报错，只能传入“how” 或者“are"或者“you”才不会报错，
> > 
> > 
> > 这个跟es无关，跟springboot有关系，首先确定“how are you” 能否到达后端！
> 
> 我之前已经确认过了，后端可以收到“how are you”,但是 esRepository.findByQuestion("how are you")就会报错~ 不知道为什么，难道是es把传入的“how are you”分词了？

`esRepository.findByQuestion("how are you")` 这段代码 是怎么实现的

**Comment by SivanCola** [comment]
在Service层，
```
@Override
    public List<xx> searchQuestion(String question) {
     return esRepository.findByQuestionLike(question);
}
```
然后在dao层，
```
public interface EsRepository extends ElasticsearchRepository<xx,String> {
    List<xx> findByQuestionLike(String question);
}
```
dao层的 findByQuestionLike是ElasticsearchRepository自己快速生成的，直接拿来用即可。

**Comment by SivanCola** [comment]
> > > > 在运行springboot后，想传入“how are you”报错，只能传入“how” 或者“are"或者“you”才不会报错，
> > > 
> > > 
> > > 这个跟es无关，跟springboot有关系，首先确定“how are you” 能否到达后端！
> > 
> > 
> > 我之前已经确认过了，后端可以收到“how are you”,但是 esRepository.findByQuestion("how are you")就会报错~ 不知道为什么，难道是es把传入的“how are you”分词了？
> 
> `esRepository.findByQuestion("how are you")` 这段代码 是怎么实现的

把service和dao层的相关代码贴出来了~

**Comment by vector4wang** [comment]
[Spring Data Elasticsearch Spring Boot version matrix](https://github.com/spring-projects/spring-data-elasticsearch/wiki/Spring-Data-Elasticsearch---Spring-Boot---version-matrix)

spring-data-elasticsearch目前只支持低版本的es吧！具体说下版本号吧，版本不同，有些用法也是有较大的不同

**Comment by SivanCola** [comment]
> [Spring Data Elasticsearch Spring Boot version matrix](https://github.com/spring-projects/spring-data-elasticsearch/wiki/Spring-Data-Elasticsearch---Spring-Boot---version-matrix)
> 
> spring-data-elasticsearch目前只支持低版本的es吧！具体说下版本号吧，版本不同，有些用法也是有较大的不同

6.3.0

**Comment by vector4wang** [comment]
> > [Spring Data Elasticsearch Spring Boot version matrix](https://github.com/spring-projects/spring-data-elasticsearch/wiki/Spring-Data-Elasticsearch---Spring-Boot---version-matrix)
> > spring-data-elasticsearch目前只支持低版本的es吧！具体说下版本号吧，版本不同，有些用法也是有较大的不同
> 
> 6.3.0

你看一下上面的链接，里面不支持6.x以上的代码！不保证没有兼容性错误！

另外我这边没有低版本号的整合，你自己打断点进去看看内部的执行过程，把最终提交给es的执行语句debug出来，看一看是不是你前端输入的wordkey，
如果是的话，那就基本上确定es把wordkey分词了；
如果不是，那就是在代码里的某个环节wordkey被切分了；

**Comment by SivanCola** [comment]
> > > [Spring Data Elasticsearch Spring Boot version matrix](https://github.com/spring-projects/spring-data-elasticsearch/wiki/Spring-Data-Elasticsearch---Spring-Boot---version-matrix)
> > > spring-data-elasticsearch目前只支持低版本的es吧！具体说下版本号吧，版本不同，有些用法也是有较大的不同
> > 
> > 
> > 6.3.0
> 
> 你看一下上面的链接，里面不支持6.x以上的代码！不保证没有兼容性错误！
> 
> 另外我这边没有低版本号的整合，你自己打断点进去看看内部的执行过程，把最终提交给es的执行语句debug出来，看一看是不是你前端输入的wordkey，
> 如果是的话，那就基本上确定es把wordkey分词了；
> 如果不是，那就是在代码里的某个环节wordkey被切分了；

好的，我先尝试，Thanks.

**Comment by vector4wang** [comment]
既然是6.3.0 建议你用jest吧，过程比较透明。你用spring-data-elasticsearch 早晚有一点是需要重构的。。。。(说多了都是泪)

**Comment by SivanCola** [comment]
> 既然是6.3.0 建议你用jest吧，过程比较透明。你用spring-data-elasticsearch 早晚有一点是需要重构的。。。。(说多了都是泪)

嗯，有这个想法。也有看到您提到过jest的好处。jest支持“how are you”这种String的查询吗？我找下开发文档

**Comment by vector4wang** [comment]
> > 既然是6.3.0 建议你用jest吧，过程比较透明。你用spring-data-elasticsearch 早晚有一点是需要重构的。。。。(说多了都是泪)
> 
> 嗯，有这个想法。也有看到您提到过jest的好处。jest支持“how are you”这种String的查询吗？我找下开发文档

当然可以了，jest只是提供了一个http的请求工具，你可以拼接任何你想要的search script, 你参照下reademe中es官方文档链接跟jest example的链接，对比一下，很容易上手

**Comment by SivanCola** [comment]
感谢，已经解决，是通过QueryBuilder创建针对两个关键词进行搜索的结果求并集来解决的。

**Comment by vector4wang** [comment]
> 感谢，已经解决，是通过QueryBuilder创建针对两个关键词进行搜索的结果求并集来解决的。

好
